import socket
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(('localhost', 2525))
print("Server: ", client.recv(1024).decode().strip())
client.send(b"HELO localhost\r\n")
print("Server: ", client.recv(1024).decode().strip())
sender = input("Enter sender email: ")
client.send(f"MAIL FROM: <{sender}>\r\n".encode())
print("Server: ", client.recv(1024).decode().strip())
recipient = input("Enter recipient email: ")
client.send(f"RCPT TO: <{recipient}>\r\n".encode())
print("Server: ", client.recv(1024).decode().strip())
client.send(b"DATA\r\n")
print("Server: ", client.recv(1024).decode().strip())
subject = input("Enter subject: ")
body = input("Enter message body: ")
message = f"Subject: {subject}\n\n{body}\n<END>"
client.send(message.encode())
print("Server: ", client.recv(1024).decode().strip())
client.send(b"QUIT\r\n")
print("Server: ", client.recv(1024).decode().strip())
client.close()